[package]
name = "qubit_device"
version = "0.0.175"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
qubit_config.workspace = true

[features]
default = []
std = []

[lints]
workspace = true
