[package]
name = "kb_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embedded-hal = "1.0.0"
# log = "0.4.27"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.11.0", features = ["rt", "critical-section-impl"] }
usb-device = "0.3.2"
usbd-hid = "0.8.2"
usbd-serial = "0.2.2"

kb_rs_derive = { path = "./kb_rs_derive" }

[features]
default = ["dev", "marble"]
dev = []
marble = []
