[graph]
targets = []
all-features = false
no-default-features = false

# [output]
# feature-depth = 1

[advisories]
unmaintained = "workspace"
ignore = []

[bans]
multiple-versions = "allow"
# wildcards = "deny"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
# * lowest-version - The path to the lowest versioned duplicate is highlighted
# * simplest-path - The path to the version with the fewest edges is highlighted
# * all - Both lowest-version and simplest-path are used
highlight = "all"
# The default lint level for `default` features for crates that are members of
# the workspace that is being checked. This can be overridden by allowing/denying
# `default` on a crate-by-crate basis if desired.
workspace-default-features = "allow"
# The default lint level for `default` features for external crates that are not
# members of the workspace. This can be overridden by allowing/denying `default`
# on a crate-by-crate basis if desired.
external-default-features = "allow"
# List of crates that are allowed. Use with care!
allow = []
# List of crates to deny
deny = []

# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
	#"ansi_term@0.11.0",
	#{ crate = "ansi_term@0.11.0", reason = "you can specify a reason why it can't be updated/removed" },
]
# Similarly to `skip` allows you to skip certain crates during duplicate
# detection. Unlike skip, it also includes the entire tree of transitive
# dependencies starting at the specified crate, up to a certain depth, which is
# by default infinite.
skip-tree = [
	#"ansi_term@0.11.0", # will be skipped along with _all_ of its direct and transitive dependencies
	#{ crate = "ansi_term@0.11.0", depth = 20 },
]

[licenses]
confidence-threshold = 0.93
allow = [
	"Apache-2.0",
	"BSD-3-Clause",
	"MIT",
	"Unicode-3.0",
	"0BSD"
]
exceptions = [
	#{ allow = ["Zlib"], crate = "adler32" },
]

#[[licenses.clarify]]
#crate = "ring"
#expression = "MIT AND ISC AND OpenSSL"
#license-files = [
# Each entry is a crate relative path, and the (opaque) hash of its contents
#{ path = "LICENSE", hash = 0xbd0eed23 }
#]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
# allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
