#![feature(file_buffered)]

use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

use proc_macro2::TokenStream;
use qubit_config::linker::output_linker_script;
use quote::{format_ident, quote};

// #[cfg(device = "supported")]
qubit_macros::import_device!(QUBIT_AUTHOR, QUBIT_MODEL);

fn keyboard_tokens() -> TokenStream {
	let processor = device::PROCESSOR.as_str();

	let keymap = device::LAYER0.0.iter().map(|row| {
		let row_tokens = row.iter().map(|&n| proc_macro2::Literal::u8_unsuffixed(n));

		quote! { [#(#row_tokens),*] }
	});

	let rows: Vec<_> = device::ROW_PINS
		.iter()
		.map(|&pin| proc_macro2::Literal::usize_unsuffixed(pin))
		.collect();

	let cols: Vec<_> = device::COL_PINS
		.iter()
		.map(|&pin| proc_macro2::Literal::usize_unsuffixed(pin))
		.collect();

	let row_pins = rows.iter().map(|r| format_ident!("gpio{r}"));
	let col_pins = cols.iter().map(|c| format_ident!("gpio{c}"));

	quote! {
		#[derive(Debug)]
		#[::qubit_macros::keyboard_matrix(
			processor = #processor,
			keymap = [#(#keymap),*],
			rows = [#(#rows),*],
			cols = [#(#cols),*]
		)]
		pub struct KeyboardMatrix;

		#[macro_export]
		macro_rules! setup_keyboard {
			($pins:ident) => {{
				$crate::codegen::KeyboardMatrix::new(
					(#($pins.#row_pins),*),
					(#($pins.#col_pins),*),
				)
			}}
		}
	}
}

fn codegen(file: &mut BufWriter<File>) {
	let device_path = {
		let author_val = env!("QUBIT_AUTHOR");
		let model_val = env!("QUBIT_MODEL");

		let author = syn::Ident::new(author_val, proc_macro2::Span::call_site());
		let model = syn::Ident::new(model_val, proc_macro2::Span::call_site());

		quote! { pub use ::qubit_device::models::#author::#model::*; }
	};

	let keyboard_tokens = keyboard_tokens();

	let tokens = quote! {
		#[comment = " This file is automatically generated and not intended for manual editing."]

		#device_path

		#keyboard_tokens
	};

	let parsed: syn::File = syn::parse2(tokens).unwrap();
	let formatted = prettyplease::unparse(&parsed);

	file.write_all(formatted.as_bytes()).unwrap();
}

fn main() {
	let out = std::env::var_os("OUT_DIR").unwrap();
	let out = PathBuf::from(out);

	let mut codegen_file = File::create_buffered(out.join("codegen.rs")).unwrap();
	codegen(&mut codegen_file);

	let processor = device::PROCESSOR;

	let memory_x = {
		const KEYMAP_SIZE: usize = device::LAYER0.get_packed_size();

		output_linker_script::<qubit_config::keyboard::KeyboardConfiguration<KEYMAP_SIZE>>(
			processor,
			device::FLASH,
			device::DEVICE,
		)
	};

	let mut f = File::create(out.join("memory.x")).unwrap();
	f.write_all(memory_x.as_bytes()).unwrap();

	println!("cargo:rustc-link-search={}", out.display());

	println!("cargo:rustc-link-arg-bins=--nmagic");
	println!("cargo:rustc-link-arg-bins=-Tlink.x");
	// println!("cargo:rustc-link-arg-bins=-Tlink-rp.x");
	println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

	println!("cargo::rustc-cfg=processor=\"{}\"", processor.as_str());
	println!("cargo::rustc-cfg=keyboard");
}
