[target.thumbv6m-none-eabi]
# flip-link doesn't support variables in the link script.
# linker = "flip-link"
runner = "elf2uf2-rs -d -s"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
