include = "./config-extend.toml"

target-applies-to-host = false

[unstable]
config-include = true
host-config = true
target-applies-to-host = true

[env]
DEFMT_LOG = "info"

[target.thumbv6m-none-eabi]
linker = "flip-link"
runner = "elf2uf2-rs -d -s"
