[package]
name = "qubit_config"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
indoc = { workspace = true, optional = true }
paste.workspace = true
semver = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
toml = { workspace = true, optional = true }

[features]
default = []
build = ["std"]
std = ["indoc", "semver/serde", "serde", "toml"]

[lints]
workspace = true
