[package]
name = "kb_rs_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.101"
proc-macro2 = "1.0.95"

# Used for their implemented traits
rp2040-hal = "0.11.0"
