name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: cargo fmt
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build_rp2040:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Install the required dependencies.
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: cargo install cargo-make flip-link

      - name: Build RP2040
        run: cargo make build --author cloudgazing --model quartz
