name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: cargo fmt
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        device:
          - { author: cloudgazing, model: quartz }
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Install the required dependencies.
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Install dependencies
        run: cargo install cargo-make flip-link

      - name: Prepare device
        run: cargo make prepare --author ${{ matrix.device.author }} --model ${{ matrix.device.model }}

      - name: Run clippy
        run: cargo clippy

      - name: Build device
        run: cargo build
